version: '3.6'
services:
  wp:
    image: wordpress:php7.3-fpm
    container_name: wordpress_production
    ports:
            - "9000:9000"
    volumes:
#      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress_uk}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-db}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-Kennedy}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: mariadb_production
    ports:
      - "3306:3306" # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-Kennedy}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-Kennedy}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress_uk}
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default_http.conf.template:/etc/nginx/conf.d/default.conf
#      - ./nginx/conf:/etc/nginx/
      - ./logs/nginx:/var/log/nginx
      - ./wp-app:/var/www/html
    depends_on:
      - wp
    restart: always

volumes:
  db_data:
